# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 10
    package-ecosystem: "composer"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"
    ignore:
        - dependency-name: "symfony/framework-bundle"
          versions: ["5.x", "6.x"]
        - dependency-name: "symfony/dotenv"
          versions: ["5.x", "6.x"]
        - dependency-name: "symfony/yaml"
          versions: ["5.x", "6.x"]
        - dependency-name: "symfony/phpunit-bridge"
          versions: ["5.x", "6.x"]
        - dependency-name: "symfony/browser-kit"
          versions: ["5.x", "6.x"]
