# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    schedule:
        interval: "daily"
    assignees:
        - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "dependency"
    ignore:
        - dependency-name: "symfony/framework-bundle"
          versions: ["5.x", "6.x"]
        - dependency-name: "symfony/dotenv"
          versions: ["5.x", "6.x"]
        - dependency-name: "symfony/yaml"
          versions: ["5.x", "6.x"]
        - dependency-name: "symfony/phpunit-bridge"
          versions: ["5.x", "6.x"]
        - dependency-name: "symfony/browser-kit"
          versions: ["5.x", "6.x"]


  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
        interval: "daily"
    assignees:
        - "zerai"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "CI dependency"

