version: "3"
services:
  php:
    image: webdevops/php-dev:7.2
    depends_on:
      - mysql
    links:
      - mysql

  nginx:
    image: webdevops/nginx:alpine
    depends_on:
      - php

  mysql:
    image: mysql:5.7.21

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"