name: Acceptance stage

on:
    workflow_call:
        # Map the workflow outputs to job outputs
        inputs:
            triggering-sha:
                required: true
                type: string
    workflow_dispatch:
        inputs:
            sha:
                description: 'SHA (full)'
                required: true


env:
    GITHUB_PAT: ${{ secrets.SF4_BOILERPLATE_GHA_PAT }}
    PHPUNIT_ARTIFACT_REPORT_FOLDER: ${{ secrets.CI_ENV_PHPUNIT_ARTIFACT_REPORT_FOLDER }}
    PHPUNIT_ARTIFACT_REPORT_NAME: ${{ secrets.CI_ENV_PHPUNIT_ARTIFACT_REPORT_NAME }}
    COVERAGE: '0'
    PHP_EXTENSIONS: ctype, curl, gd, iconv, intl, opcache, openssl, mbstring, mysql, pdo_sqlite
    PHP_EXTENSIONS_CACHE_KEY: cache-php-extensions-v1

jobs:
    triggering-workflow-info:
        runs-on: ubuntu-18.04
        name: Triggering workflow info
        steps:
            - name: Dump context
              uses: crazy-max/ghaction-dump-context@v2
            - name: Dump input triggering-sha
              run: echo triggering-sha ${{ inputs.triggering-sha }}
            - name: Dump Manual dispatch input sha
              run: echo manual dispatch sha ${{ github.event.inputs.sha }}

    dump-last-commit-message:
        runs-on: ubuntu-18.04
        timeout-minutes: 5
        steps:
            - name: Get SHA
              id: get-sha
              run: |
                  if [ "${{ github.event.inputs.sha != '' }}" ]; then
                    echo "CUSTOM_SHA=${{ github.event.inputs.sha }}" >> $GITHUB_ENV
                  else
                    echo "CUSTOM_SHA=${{ inputs.triggering-sha }}" >> $GITHUB_ENV
                  fi

            - name: Checkout
              uses: actions/checkout@v3.3.0
              with:
                  ref: ${{ env.CUSTOM_SHA }}

            - name: log commit message
              run: git log --oneline
