name: Commit stage

on: [ push ]

env:
    GITHUB_PAT: ${{ secrets.SF4_BOILERPLATE_GHA_PAT }}
    PHPUNIT_ARTIFACT_REPORT_FOLDER: ${{ secrets.CI_ENV_PHPUNIT_ARTIFACT_REPORT_FOLDER }}
    PHPUNIT_ARTIFACT_REPORT_NAME: ${{ secrets.CI_ENV_PHPUNIT_ARTIFACT_REPORT_NAME }}
    COVERAGE: '0'
    PHP_EXTENSIONS: ctype, curl, gd, iconv, intl, opcache, openssl, mbstring, mysql, pdo_sqlite
    PHP_EXTENSIONS_CACHE_KEY: cache-php-extensions-v1

jobs:
    lint-composer:
        runs-on: ubuntu-18.04
        if: "!contains(github.event.*.message, 'composer(deps')"
        timeout-minutes: 5
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: QA - Run composer validate
              uses: docker://jakzal/phpqa:php7.4-alpine
              with:
                  args: composer validate --strict --ansi
            - name: QA - Run composer normalize
              uses: docker://jakzal/phpqa:php7.4-alpine
              with:
                  args: composer normalize --dry-run --ansi


    php-cs-fixer:
        #if: ${{ github.event.workflow_run.conclusion == 'Success' }}
        name: Code style check
        runs-on: ubuntu-latest
        timeout-minutes: 20
        strategy:
            matrix:
                php:
                    - '7.2'
            fail-fast: true

        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Setup php extension cache environment
                id: cache-php-extensions
                uses: shivammathur/cache-extensions@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
            -
                name: Cache PHP extensions
                uses: actions/cache@v2
                with:
                    path: ${{ steps.cache-php-extensions.outputs.dir }}
                    key: ${{ steps.cache-php-extensions.outputs.key }}
                    restore-keys: ${{ steps.cache-php-extensions.outputs.key }}
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    ini-values: memory_limit=-1
                    coverage: none
            -
                name: Get Composer Cache Directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -
                name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -
                name: Install Composer dependencies
                run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts
            -
                name: Run PHP-CS-Fixer fix
                run: vendor/bin/php-cs-fixer fix --dry-run --diff --ansi


    php-stan:
        name: Static Analysis check (phpstan)
        runs-on: ubuntu-latest
        timeout-minutes: 20
        strategy:
            matrix:
                php:
                    - '7.2'
            fail-fast: true

        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Setup php extension cache environment
                id: cache-php-extensions
                uses: shivammathur/cache-extensions@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    key: ${{ env.PHP_EXTENSIONS_CACHE_KEY }}
            -
                name: Cache PHP extensions
                uses: actions/cache@v2
                with:
                    path: ${{ steps.cache-php-extensions.outputs.dir }}
                    key: ${{ steps.cache-php-extensions.outputs.key }}
                    restore-keys: ${{ steps.cache-php-extensions.outputs.key }}
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: ${{ env.PHP_EXTENSIONS }}
                    ini-values: memory_limit=-1
                    coverage: none
            -
                name: Get Composer Cache Directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -
                name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-
            -
                name: Install Composer dependencies
                run: composer install --prefer-dist --no-progress --no-suggest --ansi --no-scripts
            -
                name: Run PHP-CS-Fixer fix
                run: vendor/bin/phpstan analyse --ansi

